### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by rockey2020** [hengxuZ/binance-quantization#7]
Traceback (most recent call last):
  File "eth-run.py", line 2, in <module>
    from app.BinanceAPI import BinanceAPI
  File "/root/binance-quantization/app/BinanceAPI.py", line 2, in <module>
    import requests, time, hmac, hashlib
ImportError: No module named requests

**Comment by rockey2020** [comment]
改为python3 eth-run.py运行就成功了
